---
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
spec:
  containers:
    - name: mysqldb
      image: mysql:8
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: openmrs
        - name: MYSQL_USER
          value: openmrsuser
        - name: MYSQL_PASSWORD
          value: openmrs123
      volumeMounts:
        - name: dbvol
          mountPath: /var/lib/mysql
  volumes:
    - name: dbvol
      persistentVolumeClaim:
        claimName: my-aws-managed-disk